(test-directories ".")

(test 

 ;; bad translations...

 ("Bug 0113 : Translate should be mono: Bad1: {type X +-> Y}"
  :show   "Collision#Bad1"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad1"
	    ";;; Elaborating spec at $TESTDIR/Collision#S"
	    "Errors in $TESTDIR/Collision.sw"
	    "23.22-23.35	: Error in translation: Illegal to translate type X into pre-existing (and untranslated) Y"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad2: {X +-> Y}"
  :show   "Collision#Bad2"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad2"
	    "Errors in $TESTDIR/Collision.sw"
	    "24.22-24.30	: Error in translation: Illegal to translate type X into pre-existing (and untranslated) Y"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad3: {type X +-> Z, type Y +-> Z}"
  :show   "Collision#Bad3"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad3"
	    "Errors in $TESTDIR/Collision.sw"
	    "27.37-27.48	: Error in translation: Illegal to translate both type X and type Y into Z"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad4: {X +-> Z, Y +-> Z}"
  :show   "Collision#Bad4"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad4"
	    "Errors in $TESTDIR/Collision.sw"
	    "28.32-28.38	: Error in translation: Illegal to translate both type X and type Y into Z"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad5: {op f +-> g}"
  :show   "Collision#Bad5"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad5"
	    "Errors in $TESTDIR/Collision.sw"
	    "32.22-32.33	: Error in translation: Illegal to translate op f into pre-existing (and untranslated) g"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad6: {f +-> g}"
  :show   "Collision#Bad6"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad6"
	    "Errors in $TESTDIR/Collision.sw"
	    "33.22-33.30	: Error in translation: Illegal to translate op f into pre-existing (and untranslated) g"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad7: {op f +-> h, op g +-> h}"
  :show   "Collision#Bad7"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad7"
	    "Errors in $TESTDIR/Collision.sw"
	    "36.35-36.44	: Error in translation: Illegal to translate both op f and op g into h"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad8: {f +-> h, g +-> h}"
  :show   "Collision#Bad8"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad8"
	    "Errors in $TESTDIR/Collision.sw"
	    "37.32-37.38	: Error in translation: Illegal to translate both op f and op g into h"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad9: {A._ +-> B._}"
  :show   "Collision#Bad9"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad9"
	    "Errors in $TESTDIR/Collision.sw"
	    "41.22-41.34	: Error in translation: Illegal to translate type A.T into pre-existing (and untranslated) B.T"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad10: {A._ +-> C._, B._ +-> C._}"
  :show   "Collision#Bad10"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad10"
	    "Errors in $TESTDIR/Collision.sw"
	    "45.37-45.47	: Error in translation: Illegal to translate both type A.T and type B.T into C.T"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad11: {D._ +-> E._}"
  :show   "Collision#Bad11"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad11"
	    "Errors in $TESTDIR/Collision.sw"
	    "49.23-49.35	: Error in translation: Illegal to translate op D.m into pre-existing (and untranslated) E.m"
	    ""))

 ("Bug 0113 : Translate should be mono: Bad12: {D._ +-> F._, E._ +-> F._}"
  :show   "Collision#Bad12"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Bad12"
	    "Errors in $TESTDIR/Collision.sw"
	    "53.37-53.47	: Error in translation: Illegal to translate both op D.m and op E.m into F.m"
	    ""))

 ;; good, but tricky, translations...

 ("Bug 0113 : Translate should be mono: Ok1: {X +-> Y, Y +-> Z}"
  :show   "Collision#Ok1"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok1"
	    ""
	    "spec  "
	    " type Y"
	    " type Z"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  g : Y"
	    " "
	    " op  f : Y"
	    " "
	    " op  E.m : Z"
	    " "
	    " op  D.m : Z"
	    " "
	    " op  q : Z"
	    " "
	    " op  p : Y"
	    "endspec"
	    ""
	    ""))

 ("Bug 0113 : Translate should be mono: Ok2: {Y +-> Z, X +-> Y}"
  :show   "Collision#Ok2"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok2"
	    ""
	    "spec  "
	    " type Y"
	    " type Z"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  g : Y"
	    " "
	    " op  f : Y"
	    " "
	    " op  E.m : Z"
	    " "
	    " op  D.m : Z"
	    " "
	    " op  q : Z"
	    " "
	    " op  p : Y"
	    "endspec"
	    ""
	    ""))

 ("Bug 0113 : Translate should be mono: Ok3: {X +-> Y, Y +-> X}"
  :show   "Collision#Ok3"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok3"
	    ""
	    "spec  "
	    " type Y"
	    " type X"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  g : Y"
	    " "
	    " op  f : Y"
	    " "
	    " op  E.m : X"
	    " "
	    " op  D.m : X"
	    " "
	    " op  q : X"
	    " "
	    " op  p : Y"
	    "endspec"
	    ""
	    ""))

 ("Bug 0113 : Translate should be mono: Ok4: {Y +-> X, X +-> Y}"
  :show   "Collision#Ok4"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok4"
	    ""
	    "spec  "
	    " type Y"
	    " type X"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  g : Y"
	    " "
	    " op  f : Y"
	    " "
	    " op  E.m : X"
	    " "
	    " op  D.m : X"
	    " "
	    " op  q : X"
	    " "
	    " op  p : Y"
	    "endspec"
	    ""
	    ""))

 ("Bug 0113 : Translate should be mono: Ok5: {p +-> q, q +-> r}"
  :show   "Collision#Ok5"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok5"
	    ""
	    "spec  "
	    " type Y"
	    " type X"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  r : Y"
	    " "
	    " op  g : X"
	    " "
	    " op  f : X"
	    " "
	    " op  E.m : Y"
	    " "
	    " op  D.m : Y"
	    " "
	    " op  q : X"
	    "endspec"
	    ""
	    ""))

 ("Bug 0113 : Translate should be mono: Ok6: {q +-> r, p +-> q}"
  :show   "Collision#Ok6"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok6"
	    ""
	    "spec  "
	    " type Y"
	    " type X"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  r : Y"
	    " "
	    " op  g : X"
	    " "
	    " op  f : X"
	    " "
	    " op  E.m : Y"
	    " "
	    " op  D.m : Y"
	    " "
	    " op  q : X"
	    "endspec"
	    ""
	    ""))

 ("Bug 0113 : Translate should be mono: Ok7: {p +-> q, q +-> p}"
  :show   "Collision#Ok7"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok7"
	    ""
	    "spec  "
	    " type Y"
	    " type X"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  g : X"
	    " "
	    " op  f : X"
	    " "
	    " op  E.m : Y"
	    " "
	    " op  D.m : Y"
	    " "
	    " op  q : X"
	    " "
	    " op  p : Y"
	    "endspec"
	    ""
	    ""))

 ("Bug 0113 : Translate should be mono: Ok8: {q +-> p, p +-> q}"
  :show   "Collision#Ok8"
  :output '(";;; Elaborating spec-translation at $TESTDIR/Collision#Ok8"
	    ""
	    "spec  "
	    " type Y"
	    " type X"
	    " type B.T"
	    " type A.T"
	    " "
	    " op  g : X"
	    " "
	    " op  f : X"
	    " "
	    " op  E.m : Y"
	    " "
	    " op  D.m : Y"
	    " "
	    " op  q : X"
	    " "
	    " op  p : Y"
	    "endspec"
	    ""
	    ""))

 )
