#!/bin/bash --noprofile

PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:${PATH}

# set -v

# echo "  ------------------------------------------------------------------------"
# echo "  Ensure that Specware exists:"
# echo " "

# echo "  Test whether SPECWARE4 has been set."
# echo "  SPECWARE4 = [$SPECWARE4]"
# echo "  "
if [ -z "$SPECWARE4" ]; then
    echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
    exit 1
fi

# ------------------------------------------------------------------------

# echo "  Test whether SPECWARE4 is a directory."
# echo "  Testing $SPECWARE4"
# echo "  "

if [ ! -d "$SPECWARE4" ]; then
   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
   exit 1
fi

# ------------------------------------------------------------------------

# echo "  Ensure SPECWARE4 is set to full pathname."
# echo "  "

case "$SPECWARE" in
    /*) : ok;;
    *)  SPECWARE="`pwd`/$SPECWARE";;
esac

# ------------------------------------------------------------------------

# echo "  Test whether (revised) SPECWARE4 has been set."
# echo "  SPECWARE4 = [$SPECWARE4]"
# echo "  "

if [ -z "$SPECWARE4" ]; then
    echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
    exit 1
fi

# ------------------------------------------------------------------------

# echo "  Test whether (revised) SPECWARE4 is a directory."
# echo "  Testing $SPECWARE4"
# echo "  "

if [ ! -d "$SPECWARE4" ]; then
   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
   exit 1
fi

# ------------------------------------------------------------------------

# echo "  Ensure SPECWARE4 is set to full pathname (again?)."
# echo "  "

case "$SPECWARE" in
    /*) : ok;;
    *)  SPECWARE="`pwd`/$SPECWARE";;
esac

# ------------------------------------------------------------------------

# echo "  Ensure Specware image exists."
# echo "  Testing $SPECWARE4/Applications/Specware/bin/unix/Specware4.$IMAGE_EXTENSION"
# echo "  "

if [ ! -d "$SPECWARE4"/Applications/Specware ]; then
   echo "Failed to $act: could not find directory
   $SPECWARE4/Applications/Specware" 2>&1
   exit 1
fi

if [ ! -f "$SPECWARE4"/Applications/Specware/bin/unix/Specware4."$IMAGE_EXTENSION" ]; then
   echo "Failed to $act: could not find specware image
   $SPECWARE4/Applications/Specware/bin/unix/Specware4.$IMAGE_EXTENSION" 2>&1
   exit 1
fi

echo "  SPECWARE4 = [$SPECWARE4]"

# Happy...
# Don't exit explicitly -- this script gets included in others via bash's . convention

