#!/bin/bash --noprofile
# set -v

SCRIPTDIR=`/usr/bin/dirname $0`

export LISP_MODE="ACL"
export FASL_EXTENSION="fasl"
export IMAGE_EXTENSION="dxl"
export EXECUTABLE_EXTENSION="exe"

echo "  ------------------------------------------------------------------------"
echo "  Verify_ACL:  Ensure that Allegro CL executable exists:"
echo "  "

for L in /usr/local/acl/acl62/alisp /usr/local/acl/acl61/alisp /usr/local/acl/acl501/lisp; do
  if [ -x "$L" ]; then
    export LISP="$L"; break
  fi
done

if [ -z "$LISP" ]; then
  echo "  Verify_ACL:  Could not find ACL lisp"
  exit 1
fi

LISP_DIR=`/usr/bin/dirname $LISP`
export LISP_VERSION=`/bin/basename ${LISP_DIR}`
export BIG_ALISP="${BIN_DIR}/big-alisp-${LISP_VERSION}.${IMAGE_EXTENSION}"
export BATCH_LISP="$LISP -I ${BIG_ALISP} -batch"
export BATCH_SPECWARE="$LISP -I $SPECWARE4/Applications/Specware/bin/linux/Specware4.${IMAGE_EXTENSION} -batch"

echo "  Verify_ACL:  LISP_MODE            = [$LISP_MODE]"
echo "  Verify_ACL:  LISP                 = [$LISP]"
echo "  Verify_ACL:  LISP_VERSION         = [$LISP_VERSION]"
echo "  Verify_ACL:  FASL_EXTENSION       = [$FASL_EXTENSION]"
echo "  Verify_ACL:  IMAGE_EXTENSION      = [$IMAGE_EXTENSION]"
echo "  Verify_ACL:  EXECUTABLE_EXTENSION = [$EXECUTABLE_EXTENSION]"
echo "  Verify_ACL:  BATCH_LISP           = [$BATCH_LISP]"
echo "  Verify_ACL:  BATCH_SPECWARE       = [$BATCH_SPECWARE]"
echo "  "

if [ -f "${BIG_ALISP}" ]; then
	echo "  Verify_ACL:  Already have ${BIG_ALISP}"
else
	echo "  Verify_ACL:  Building ${BIG_ALISP}"
	# big-alisp.dxl will have a larger lisp heap than the default alisp image.
	$LISP -batch <<-XXXX
	  (build-lisp-image "${BIG_ALISP}" :lisp-heap-start #x48000000 :oldspace #x100)
	XXXX
	RC=$?
	if [ $RC -ne 0 ]; then        
	  echo "  "                
	  echo "  Verify_ACL:  Problem building big alisp image.  RC = $RC"
	  exit 1
        fi
fi


