#!/bin/bash --noprofile

PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:${PATH}

# set -v

echo "  ------------------------------------------------------------------------"
echo "  Verify_Specware4:  Ensure that SPECWARE4 shell variable is set:"
echo "  "

if [ -z "$SPECWARE4" ]; then
  SCRIPTDIR=`/usr/bin/dirname $0`
  echo "  Verify_Specware4:  SCRIPTDIR = [$SCRIPTDIR]"
  cd $SCRIPTDIR
  SCRIPTDIR=`pwd`
  echo "  Verify_Specware4:  SCRIPTDIR = [$SCRIPTDIR]"
  PARENTDIR=`/usr/bin/dirname $SCRIPTDIR`
  SPECWARE4=`/usr/bin/dirname $PARENTDIR`
fi

export SPECWARE4

export APP_NAME="Specware4"
export APP_DIR="$SPECWARE4/Applications/Specware"
export GEN_DIR="$APP_DIR/lisp"
export BIN_DIR="$APP_DIR/bin/unix"
# export SOURCES_DIR="$APP_DIR/Sources"
export SWPATH=".:/"
export MAIN_COMPILE_FILE="$APP_DIR/bin/unix/compile-and-load-specware4.lisp"
export MAIN_BUILD_FILE="$APP_DIR/bin/unix//load-specware4.lisp"

echo "  Verify_Specware4:  APP_NAME          = [$APP_NAME]"
echo "  Verify_Specware4:  SPECWARE4         = [$SPECWARE4]"
echo "  Verify_Specware4:  APP_DIR           = [$APP_DIR]"
echo "  Verify_Specware4:  GEN_DIR           = [$GEN_DIR]"
echo "  Verify_Specware4:  BIN_DIR           = [$BIN_DIR]"
echo "  Verify_Specware4:  SWPATH            = [$SWPATH]"
echo "  Verify_Specware4:  MAIN_COMPILE_FILE = [$MAIN_COMPILE_FILE]"
echo "  Verify_Specware4:  MAIN_BUILD_FILE   = [$MAIN_BUILD_FILE]"
echo "  "

# Happy...
# Don't exit explicitly -- this script gets included in others via bash's . convention


