#!/bin/bash --noprofile
# set -v

SCRIPTDIR=`/usr/bin/dirname $0`

export LISP_MODE="SBCL"
export FASL_EXTENSION="sfsl"
export IMAGE_EXTENSION="sbclimage"
export EXECUTABLE_EXTENSION="sbclimage"

echo "  ------------------------------------------------------------------------"
echo "  Verify_SBCL:  Ensure that SBCL executable exists:"
echo " "

for L in /usr/local/bin/sbcl "$HOME"/bin/sbcl /bin/lisp; do
  if [ -x "$L" ]; then
    export LISP="$L"; break
  fi
done

if [ -z "$LISP" ]; then
  echo "  Verify_SBCL:  Could not find SBCL lisp"
  exit 1
fi

export BIG_LISP="$LISP --dynamic-space-size 880 --end-runtime-options"
export LISP_VERSION="SBCL"
export BATCH_LISP="$BIG_LISP"

# From sbcl web page:
#================================================================================  
# sbcl runtime-option* --end-runtime-options toplevel-option* --end-toplevel-options user-options*
#================================================================================  
# runtime options:
#
#  -core corefilename
#      Run the specified Lisp core file instead of the default. 
#      Note that if the Lisp core file is a user-created core file, 
#      it may run a nonstandard toplevel which does not recognize the standard toplevel options.
#  --dynamic-space-size megabytes
#      Size of the dynamic space reserved on startup in megabytes. 
#      Default value is platform dependent.
#  --noinform
#      Suppress the printing of any banner or other informational message at startup. 
#      This makes it easier to write Lisp programs which work cleanly in Unix pipelines. 
#      See also the --noprint and --disable-debugger options.
#  --help
#      Print some basic information about SBCL, then exit.
#  --version
#      Print SBCL's version information, then exit. 
#================================================================================  

# -dynamic-space-size should be at least about 530 (MByte) for Accord
# be careful to use double-dash!  "-dynatmic-space-size 800" would be silently ignored!
# 512 is default
# 1000 is too large

export BATCH_SPECWARE=${BATCH_SPECWARE:-"$SPECWARE4/Applications/Specware/bin/linux/Specware4.${IMAGE_EXTENSION} --dynamic-space-size 880 --end-runtime-options"}
export BATCH_BOOTSTRAP=${BATCH_BOOTSTRAP:-"$SPECWARE4/Applications/Specware/bin/linux/Bootstrap.${IMAGE_EXTENSION} --dynamic-space-size 880 --end-runtime-options"}

echo " "
echo "  Verify_SBCL:  LISP_MODE            = [$LISP_MODE]"
echo "  Verify_SBCL:  LISP                 = [$LISP]"
echo "  Verify_SBCL:  BIG_LISP             = [$BIG_LISP]"
echo "  Verify_SBCL:  LISP_VERSION         = [$LISP_VERSION]"
echo "  Verify_SBCL:  FASL_EXTENSION       = [$FASL_EXTENSION]"
echo "  Verify_SBCL:  IMAGE_EXTENSION      = [$IMAGE_EXTENSION]"
echo "  Verify_SBCL:  EXECUTABLE_EXTENSION = [$EXECUTABLE_EXTENSION]"
echo "  Verify_SBCL:  BATCH_LISP           = [$BATCH_LISP]"
echo "  Verify_SBCL:  BATCH_SPECWARE       = [$BATCH_SPECWARE]"
echo "  Verify_SBCL:  BATCH_BOOTSTRAP      = [$BATCH_BOOTSTRAP]"
echo "  "
