#!/bin/bash --noprofile
# set -v

SCRIPTDIR=`/usr/bin/dirname $0`

if [ -z "$BIN_DIR" ]; then
 echo "Need to set BIN_DIR before calling Verify_ACL"
 exit 1
fi

export LISP_MODE="ACL"
export FASL_EXTENSION="fasl"
export IMAGE_EXTENSION="dxl"
export EXECUTABLE_EXTENSION="exe"

echo "  ------------------------------------------------------------------------"
echo "  Verify_ACL:  Ensure that Allegro CL executable exists:"
echo "  "

for L in /usr/local/acl/acl62/alisp /usr/local/acl/acl80/alisp /usr/local/acl/acl70/alisp /usr/local/acl/acl61/alisp /usr/local/acl/acl501/lisp /usr/local/acl80/alisp; do
  if [ -x "$L" ]; then
    export LISP="$L"; break
  fi
done

if [ -z "$LISP" ]; then
  echo "  Verify_ACL:  Could not find ACL lisp"
  exit 1
fi

if [ ! -x "$LISP" ]; then
   echo " Verify_ACL:  $LISP is not executable"
   exit 1
fi

LISP_DIR=`/usr/bin/dirname $LISP`
export LISP_VERSION=`/bin/basename ${LISP_DIR}`
export BIG_LISP="${BIN_DIR}/big-alisp-${LISP_VERSION}.${IMAGE_EXTENSION}"
export BATCH_LISP="$LISP -I ${BIG_LISP} -batch"
export BATCH_SPECWARE=${BATCH_SPECWARE:-"$LISP -I $SPECWARE4/Applications/Specware/bin/unix/Specware4.${IMAGE_EXTENSION} -batch"}
export BATCH_BOOTSTRAP=${BATCH_BOOTSTRAP:-"$LISP -I $SPECWARE4/Applications/Specware/bin/unix/Bootstrap.${IMAGE_EXTENSION} -batch"}

echo " "
echo "  Verify_ACL:  LISP_MODE            = [$LISP_MODE]"
echo "  Verify_ACL:  LISP                 = [$LISP]"
echo "  Verify_ACL:  BIG_LISP             = [$BIG_LISP]"
echo "  Verify_ACL:  LISP_VERSION         = [$LISP_VERSION]"
echo "  Verify_ACL:  FASL_EXTENSION       = [$FASL_EXTENSION]"
echo "  Verify_ACL:  IMAGE_EXTENSION      = [$IMAGE_EXTENSION]"
echo "  Verify_ACL:  EXECUTABLE_EXTENSION = [$EXECUTABLE_EXTENSION]"
echo "  Verify_ACL:  BATCH_LISP           = [$BATCH_LISP]"
echo "  Verify_ACL:  BATCH_SPECWARE       = [$BATCH_SPECWARE]"
echo "  Verify_ACL:  BATCH_BOOTSTRAP      = [$BATCH_BOOTSTRAP]"
echo "  "

if [ -f "${BIG_LISP}" ]; then
	echo "  Verify_ACL:  Already have ${BIG_LISP}"
else
	NOW=`/bin/date +"%y%m%d-%H%M%S"`
	# big-alisp.dxl will have a larger lisp heap than the default alisp image.
	echo "  Verify_ACL:  Building ${BIG_LISP}"
	echo "               See /tmp/build-big-alisp-$NOW.log for details."
	$LISP -batch <<-XXXX>> /tmp/build-big-alisp-$NOW.log
	  (build-lisp-image "${BIG_LISP}" :lisp-heap-start #x48000000 :oldspace #x100)
	XXXX
	RC=$?
	if [ $RC -ne 0 ]; then        
	  echo "  "                
	  echo "  Verify_ACL:  Problem building big alisp image.  RC = $RC"
	  exit 1
        fi
fi





