#!/bin/bash --noprofile
# set -v

SCRIPTDIR=`/usr/bin/dirname $0`

export LISP_MODE="CMUCL"
export FASL_EXTENSION="x86f"
export IMAGE_EXTENSION="cmuimage"
export EXECUTABLE_EXTENSION="cmuimage"

echo "  ------------------------------------------------------------------------"
echo "  Verify_CMUCL:  Ensure that CMU CL executable exists:"
echo " "

for L in "$HOME"/cmucl/bin/lisp /usr/share/cmulisp/bin/lisp /usr/local/bin/cmucl; do
  if [ -x "$L" ]; then
    export LISP="$L"; break
  fi
done

if [ -z "$LISP" ]; then
  echo "  Verify_CMUCL:  Could not find CMUCL lisp"
  exit 1
fi

export LISP_VERSION="CMUCL"
export BATCH_LISP="$LISP -batch"
export BATCH_SPECWARE="$LISP -core $SPECWARE4/Applications/Specware/bin/linux/Specware4.${IMAGE_EXTENSION} -batch"

echo "  Verify_CMUCL:  LISP_MODE            = [$LISP_MODE]"
echo "  Verify_CMUCL:  LISP                 = [$LISP]"
echo "  Verify_CMUCL:  LISP_VERSION         = [$LISP_VERSION]"
echo "  Verify_CMUCL:  FASL_EXTENSION       = [$FASL_EXTENSION]"
echo "  Verify_CMUCL:  IMAGE_EXTENSION      = [$IMAGE_EXTENSION]"
echo "  Verify_CMUCL:  EXECUTABLE_EXTENSION = [$EXECUTABLE_EXTENSION]"
echo "  Verify_CMUCL:  BATCH_LISP           = [$BATCH_LISP]"
echo "  Verify_CMUCL:  BATCH_SPECWARE       = [$BATCH_SPECWARE]"
echo "  "
