#!/bin/bash --noprofile

PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:/usr/local/bin

LISP_MODE=$1

if [ -f $SPECWARE4/Scripts/unix/Verify_${LISP_MODE} ]; then
  # bash convention for . means the file is processed inline (as if copied here)
  . $SPECWARE4/Scripts/unix/Verify_${LISP_MODE}
else
  echo "  Verify_Lisp: Unrecognized lisp mode.  LISP_MODE = [$LISP_MODE]"
  exit 1
fi

