#!/bin/bash

cd `/usr/bin/dirname $0`/../../..
SCRIPTDIR=`pwd`
EMACS_SPECWARE="$SCRIPTDIR"/Emacs_Specware

# Basic
PATH=/bin:/usr/local/bin:/usr/bin:/sbin:/usr/sbin:$HOME/bin:${PATH}
# Isabelle, fink, darwinports
PATH=/Applications/Isabelle2011.app/Isabelle/bin:/sw/bin:/opt/local/bin:/opt/local/sbin:$HOME/Applications/Isabelle2011.app/Isabelle/bin:${PATH}

isabelle emacs -p "$EMACS_SPECWARE" $* 