#!/bin/sh
(shopt -s igncr) 2>/dev/null && shopt -s igncr;  # Ignore cr's

Prior_EMACS="$EMACS"

#########################################################################

OLD_PATH=$PATH
PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:/usr/local/bin:${PATH}

EMACS=`which emacs`

if [ -z "$EMACS" ]; then
   echo "Failed to $act, no EMACS executable found" 2>&1
   exit 1
fi

if [ ! -x "$EMACS" ]; then
   echo "Failed to $act, $EMACS is not executable" 2>&1
   exit 1
fi
PATH="$OLD_PATH"

export EMACS

#########################################################################

echo ""
echo "prior EMACS: $Prior_EMACS"
echo "final EMACS: $EMACS"
echo ""





