#!/bin/sh
(shopt -s igncr) 2>/dev/null && shopt -s igncr;  # Ignore cr's

# Ensure SWPATH is set

Prior_SWPATH="$SWPATH"

############################################################################

if [ -z "$SWPATH" ]; then
  SWPATH="C:/cygwin;/"
  export SWPATH
fi

############################################################################

export SWPATH

echo  ""
echo  "prior SWPATH: $Prior_SWPATH"
echo  "final SWPATH: $SWPATH"
echo  ""

