#!/bin/bash

cd $SPECWARE4/Languages/PSL/Semantics
ln -s ../../SpecCalculus/Semantics/Specware.sw .
ln -s ../../SpecCalculus/Semantics/SpecPath.sw .
ln -s ../../SpecCalculus/Semantics/Environment.sw .

cd $SPECWARE4/Languages/PSL/Semantics/Evaluate
# files...
ln -s ../../../SpecCalculus/Semantics/Evaluate/Colimit.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Diagram.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/DiagMorphism.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Generate.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Let.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Obligations.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Qualify.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Snark.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Spec.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/SpecMorphism.sw .
# ln -s ../../../SpecCalculus/Semantics/Evaluate/Substitute.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Translate.sw .
ln -s ../../../SpecCalculus/Semantics/Evaluate/URI.sw .
# directories...
ln -s ../../../SpecCalculus/Semantics/Evaluate/Spec .
ln -s ../../../SpecCalculus/Semantics/Evaluate/Substitute .
ln -s ../../../SpecCalculus/Semantics/Evaluate/URI .
