;; These two definitions might not be needed here
;; They are in BuildPreamble.lisp where they are needed
(defvar Accord-version "4.0.11")
(defvar Accord-version-name "Specware-4-0-11")
(defvar Accord-name "Specware-Accord")	; Name of directory and startup files
(defvar Accord-dir (sys:getenv "ACCORD"))
(defvar Specware-dir (sys:getenv "SPECWARE4"))
(defun in-accord-dir (file) (concatenate 'string Accord-dir "/" file))
(defun in-specware-dir (file) (concatenate 'string Specware-dir "/" file))
(defun in-lisp-dir (file) (concatenate 'string (sys:getenv "ALLEGRO") "/" file))

;; This is the sub-directory to receive this particular distribution.
;; In particular, this is where generate-application puts all its stuff.
(defparameter distribution-directory 
  (in-accord-dir  (concatenate 'string "distribution/" Accord-name "/")))
(defun in-distribution-dir (file) (concatenate 'string distribution-directory file))

;; If the application directory already exists, then we delete it.
;; generate-application complains and dies if the directory exists.
(when (probe-file distribution-directory)
  (excl::delete-directory-and-files distribution-directory))

(generate-application
  ;; this is the name of the application
  Accord-name

  ;; this is the directory where the application is to go
  ;; (plus accompanying files) 
  distribution-directory

  ;; a list of files to load
  (mapcar #'(lambda (file) (format nil "~A/Applications/Specware/Handwritten/Lisp/~A.lisp" 
				   Specware-dir
				   file))
	  '("BuildAccordPreamble" "Specware4" "load-accord" "accord-license"))

  ;; a list of files to copy to the distribution directory
  :application-files
  (list ;;; (in-accord-dir "/Library/")
	;;; (in-accord-dir "/Applications/Accord/Courses/")
   (in-specware-dir "Release/Windows/Specware-Accord.cmd"))

  ;; Possible option instead of excl::delete-directory-and-files call
  ;;  :allow-existing-directory t

  ;; the image does not have a compiler neither during the build nor after.
  ;; The application has the interpreter only.
  :include-compiler nil

  ;; which runtime? the other option is :dynamic which includes the compiler
  :runtime :standard
  )

;;; Copy needed directories to distribution
(copy-directory (in-specware-dir "Library/Base/")
		(in-distribution-dir "Library/Base/"))
(copy-directory (in-specware-dir "Library/Accord/")
		(in-distribution-dir "Library/Accord/"))
(specware::copy-file (in-specware-dir "Library/Base.sw")
                     (in-distribution-dir "Library/Base.sw"))
(copy-directory (in-specware-dir "Library/IO/Emacs/")
		(in-distribution-dir "Library/IO/Emacs/"))
(copy-directory (in-specware-dir "UserDoc/tutorial/example/")
		(in-distribution-dir "Examples/Matching/"))
(copy-directory (in-specware-dir "UserDoc/examples/")
		(in-distribution-dir "Examples/"))
(specware::make-directory (in-distribution-dir "Documentation/"))
(specware::copy-file (in-specware-dir "UserDoc/language-manual/SpecwareLanguageManual.pdf")
 	   (in-distribution-dir "Documentation/SpecwareLanguageManual.pdf"))
(specware::copy-file (in-specware-dir "UserDoc/tutorial/SpecwareTutorial.pdf")
 	   (in-distribution-dir "Documentation/SpecwareTutorial.pdf"))
(specware::copy-file (in-specware-dir "UserDoc/user-manual/SpecwareUserManual.pdf")
 	   (in-distribution-dir "Documentation/SpecwareUserManual.pdf"))
(specware::copy-file (in-specware-dir "UserDoc/cheat-sheet/Specware-405-QuickReference.pdf")
 	   (in-distribution-dir "Documentation/Specware-QuickReference.pdf"))

(copy-directory (in-accord-dir "Sources/Handwritten/")
		(in-distribution-dir "Sources/Handwritten/"))

(copy-directory (in-lisp-dir "xeli/")
		(in-distribution-dir "Library/IO/Emacs/xeli/"))

(specware::make-directory (in-distribution-dir "Languages/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/doc"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests"))
(specware::make-directory (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Examples"))

(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/reclaim.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/reclaim.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/allchblk.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/allchblk.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/misc.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/misc.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/alloc.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/alloc.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mach_dep.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mach_dep.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/os_dep.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/os_dep.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mark_rts.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mark_rts.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/headers.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/headers.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mark.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mark.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/obj_map.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/obj_map.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pcr_interface.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pcr_interface.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/blacklst.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/blacklst.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/finalize.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/finalize.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/new_hblk.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/new_hblk.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/real_malloc.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/real_malloc.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/dyn_load.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/dyn_load.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/dbg_mlc.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/dbg_mlc.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/malloc.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/malloc.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/stubborn.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/stubborn.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/checksums.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/checksums.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/solaris_threads.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/solaris_threads.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/aix_irix_threads.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/aix_irix_threads.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pthread_support.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pthread_support.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pthread_stop_world.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pthread_stop_world.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/darwin_stop_world.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/darwin_stop_world.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/typd_mlc.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/typd_mlc.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ptr_chck.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ptr_chck.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mallocx.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mallocx.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/solaris_pthreads.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/solaris_pthreads.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gcj_mlc.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gcj_mlc.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/specific.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/specific.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc_dlopen.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc_dlopen.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/backgraph.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/backgraph.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/win32_threads.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/win32_threads.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mips_sgi_mach_dep.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mips_sgi_mach_dep.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/rs6000_mach_dep.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/rs6000_mach_dep.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/alpha_mach_dep.S") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/alpha_mach_dep.S"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/sparc_mach_dep.S") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/sparc_mach_dep.S"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_typed.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_typed.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_hdrs.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_hdrs.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_priv.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_priv.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gcconfig.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gcconfig.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_pmark.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_pmark.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_inl.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_inl.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_inline.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_inline.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_mark.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_mark.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/threadlibs.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/threadlibs.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/if_mach.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/if_mach.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/if_not_there.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/if_not_there.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc_cpp.cc") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc_cpp.cc"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_cpp.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_cpp.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gcname.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gcname.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/weakpointer.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/weakpointer.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_locks.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/gc_locks.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gcc_support.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gcc_support.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mips_ultrix_mach_dep.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mips_ultrix_mach_dep.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_alloc.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_alloc.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/new_gc_alloc.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/new_gc_alloc.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_allocator.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_allocator.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/javaxfc.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/javaxfc.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/sparc_sunos4_mach_dep.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/sparc_sunos4_mach_dep.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/sparc_netbsd_mach_dep.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/sparc_netbsd_mach_dep.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/solaris_threads.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/solaris_threads.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_backptr.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_backptr.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/hpux_test_and_clear.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/hpux_test_and_clear.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_gcj.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_gcj.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_local_alloc.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_local_alloc.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/dbg_mlc.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/dbg_mlc.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/specific.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/specific.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/powerpc_darwin_mach_dep.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/powerpc_darwin_mach_dep.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/leak_detector.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/leak_detector.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_amiga_redirects.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_amiga_redirects.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_pthread_redirects.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_pthread_redirects.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ia64_save_regs_in_stack.s") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ia64_save_regs_in_stack.s"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_config_macros.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/gc_config_macros.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/pthread_support.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/pthread_support.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/pthread_stop_world.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/pthread_stop_world.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/darwin_semaphore.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/darwin_semaphore.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/darwin_stop_world.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/darwin_stop_world.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordbscs.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordbscs.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordxtra.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordxtra.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordprnt.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordprnt.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordtest.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/cordtest.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/cord.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/cord.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/ec.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/ec.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/cord_pos.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/private/cord_pos.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_cmds.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_cmds.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.ICO") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.ICO"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.RC") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/cord/de_win.RC"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/README.QUICK") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/README.QUICK"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/setjmp_t.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/setjmp_t.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/callprocs") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/callprocs"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pc_excludes") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/pc_excludes"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/MacProjects.sit.hqx") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/MacProjects.sit.hqx"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/MacOS.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/MacOS.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/datastart.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/datastart.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/dataend.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/dataend.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/MacOS_config.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/MacOS_config.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/MacOS_Test_config.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Mac_files/MacOS_Test_config.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/add_gc_prefix.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/add_gc_prefix.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc_cpp.cpp") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc_cpp.cpp"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/version.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/version.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/AmigaOS.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/AmigaOS.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/test.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/test.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/test_cpp.cc") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/test_cpp.cc"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/trace_test.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/trace_test.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/leak_test.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/leak_test.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/thread_leak_test.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/tests/thread_leak_test.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/configure.in") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/configure.in"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.am") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.am"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/configure") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/configure"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/acinclude.m4") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/acinclude.m4"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/libtool.m4") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/libtool.m4"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/install-sh") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/install-sh"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/configure.host") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/configure.host"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.in") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.in"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ltconfig") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ltconfig"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/aclocal.m4") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/aclocal.m4"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/config.sub") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/config.sub"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/config.guess") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/config.guess"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/Makefile.am") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/Makefile.am"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/Makefile.in") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/include/Makefile.in"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ltmain.sh") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/ltmain.sh"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mkinstalldirs") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/mkinstalldirs"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/depcomp") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/depcomp"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/missing") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/missing"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/OS2_MAKEFILE") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/OS2_MAKEFILE"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/NT_MAKEFILE") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/NT_MAKEFILE"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/NT_THREADS_MAKEFILE") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/NT_THREADS_MAKEFILE"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc.mak") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/gc.mak"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/BCC_MAKEFILE") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/BCC_MAKEFILE"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/EMX_MAKEFILE") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/EMX_MAKEFILE"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/WCC_MAKEFILE") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/WCC_MAKEFILE"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.dj") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.dj"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/PCR-Makefile") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/PCR-Makefile"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/SMakefile.amiga") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/SMakefile.amiga"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.DLLs") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.DLLs"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/digimars.mak") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/digimars.mak"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.direct") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/gc6.2/Makefile.direct"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/Makerules") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/Makerules"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/SWC_Common.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/SWC_Common.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/SWC_Memory.h") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/SWC_Memory.h"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Clib/SWC_Memory.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Clib/SWC_Memory.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Examples/Makefile") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Examples/Makefile"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Examples/QuickSortWithMain.sw") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Examples/QuickSortWithMain.sw"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Examples/QuickSort.sw") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Examples/QuickSort.sw"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Examples/main.c") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Examples/main.c"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Examples/queens.sw") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Examples/queens.sw"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/Examples/BitString.sw") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/Examples/BitString.sw"))
(specware::copy-file (in-specware-dir "Languages/MetaSlang/CodeGen/C/README.CCodeGen") (in-distribution-dir "Languages/MetaSlang/CodeGen/C/README.CCodeGen"))

