#!/bin/sh

act='launch Specware in Allegro CL, using Allegro xeli interface to XEmacs'

########################################################################

OLD_PATH=$PATH
PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:/usr/local/bin:${PATH}

# Use the directory of this file as the default value of SPECWARE4
# Note: $0 may refer to Specware or SpecwareShell script invoking this...

INVOKED_HERE=`dirname $0`
cd $INVOKED_HERE
HERE=`pwd`
PATH=$OLD_PATH

########################################################################

. $HERE/Find_SPECWARE4
. $HERE/Find_ACL
. $HERE/Update_Path
. $HERE/Update_SWPATH
. $HERE/Find_Specware_App_ACL
. $HERE/Find_XEMACS

########################################################################

$XEMACS -geometry 180x70+180+2 -name  "Specware" -title "Specware" \
        -l "$LISP_DIR"/xeli/fi-site-init \
        -l "$SPECWARE4"/Library/IO/Emacs/load \
        $* \
        -f run-specware4 &

