#!/bin/sh

act='launch Specware in CMUCL, no XEmacs'

OLD_PATH=$PATH
PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:/usr/local/bin

# Use the directory of this file as the default value of SPECWARE4
# Note: $0 may refer to Specware or SpecwareShell script invoking this...

INVOKED_HERE=`dirname $0`
cd $INVOKED_HERE
HERE=`pwd`

. $HERE/Find_Specware4
. $HERE/Find_CMUCL

LISP_HEAP_IMAGE="$SPECWARE4"/Specware4.cmuimage
echo  "LISP_HEAP_IMAGE = $LISP_HEAP_IMAGE"
export LISP_HEAP_IMAGE

# . $HERE/Find_XEmacs

PATH=$OLD_PATH

"$LISP" -core "$LISP_HEAP_IMAGE" -eval "(progn (setq emacs::*use-emacs-interface?* nil) (Specware::initializeSpecware-0) (SWShell::specware-shell t) (exit))"
