#!/bin/sh

# Basic
PATH=/bin:/usr/local/bin:/usr/bin:/sbin:/usr/sbin:$HOME/bin:${PATH}
# fink, darwinports
PATH=/usr/local/Isabelle/bin:/sw/bin:/opt/local/bin:/opt/local/sbin:$HOME/Isabelle/bin:${PATH}

xemacs=`which xemacs`
act='launch Specware'

if [ -z "$xemacs" ]; then
  xemacs="/sw/bin/xemacs"
fi

PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:${PATH}

# Use the directory of this file as the value of SPECWARE4
cd `dirname $0`/../../..
SPECWARE4=`pwd`
export SPECWARE4

# Test whether SPECWARE4 has been set

if [ -z "$SPECWARE4" ]; then
    echo "Failed to $act, SPECWARE4 environment variable not set" 2>&1
    exit 1
fi

# Test whether SPECWARE4 is a directory

if [ ! -d "$SPECWARE4" ]; then
   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
   exit 1
fi

# Ensure SWPATH is set

if [ -z "$SWPATH" ]; then
  SWPATH="/"
  export SWPATH
fi

LISP_EXECUTABLE="$SPECWARE4"/Specware4.sbclexe
LISP_HEAP_IMAGE=NONE
LISP_DIRECTORY="$SPECWARE4"/
SPECWARE_INIT_FORM=NIL
export LISP_EXECUTABLE
export LISP_HEAP_IMAGE
export LISP_DIRECTORY
export SPECWARE_INIT_FORM

$xemacs -l "$SPECWARE4"/Library/IO/Emacs/load-slime -f run-specware4 &
