#!/bin/sh

# To get SPECWARE4, go up one directory level and then back down to Specware4.
# If we are connected to Accord or some other sibling, we'll get to 
# the right place, and if we are already connected to Specware4, 
# this will just be some wasted motion.

# Note: $0 may refer to a Specware or SpecwareShell script invoking this...

DIR_OF_INVOKED_SCRIPT=`dirname "$0"`
PARENT=`dirname "$DIR_OF_INVOKED_SCRIPT"`
cd "$PARENT/Specware-4-2-4"
NEW_SPECWARE4="`pwd`"

Prior_SPECWARE4="$SPECWARE4"

#########################################################################
# Warn if this changes SPECWARE4.

if [ "$SPECWARE4" == "" ]; then
   : do nothing
elif [ "$SPECWARE4" == "$NEW_SPECWARE4" ]; then
   : do nothing
else
   echo "Revising SPECWARE4"
fi

SPECWARE4=$NEW_SPECWARE4

# Test whether SPECWARE4 is a directory

if [ ! -d "$SPECWARE4" ]; then
   echo  "SPECWARE4       = $SPECWARE4"
   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
   exit 1
fi

export SPECWARE4

#########################################################################

echo ""
echo "prior SPECWARE4: $Prior_SPECWARE4"
echo "final SPECWARE4: $SPECWARE4"
echo ""



