#!/bin/sh

# Note: $0 may refer to a Specware or SpecwareShell script invoking this...

INVOKED_HERE=`dirname $0`
cd "$INVOKED_HERE"
HERE="`pwd`"

Prior_SPECWARE4="$SPECWARE4"

#########################################################################
# Use the directory of this file as the default value of SPECWARE4
# Warn if this changes it.

if [ "$SPECWARE4" == "" ]; then
   : do nothing
elif [ "$SPECWARE4" == "$INVOKED_HERE" ]; then
   : do nothing
elif [ "$SPECWARE4" == "$HERE" ]; then
   : do nothing
else
   echo "Ignoring prior SPECWARE4 : $SPECWARE4"
fi

SPECWARE4=$HERE

# Test whether SPECWARE4 is a directory

if [ ! -d "$SPECWARE4" ]; then
   echo  "SPECWARE4       = $SPECWARE4"
   echo "Failed to $act, $SPECWARE4 is not a directory" 2>&1
   exit 1
fi

# Ensure SPECWARE4 is set to full pathname:

case "$SPECWARE4" in
    .)  SPECWARE4=`pwd`;;
    /*) : do nothing ;;
    *)  SPECWARE4="`pwd`/$SPECWARE4";;
esac

export SPECWARE4

#########################################################################

echo ""
echo "prior SPECWARE4: $Prior_SPECWARE4"
echo "final SPECWARE4: $SPECWARE4"
echo ""



