#!/bin/sh

OLD_PATH=$PATH
PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:/usr/local/bin

XEMACS=`which xemacs`

if [ -z "$XEMACS" ]; then
   echo "Failed to $act, no XEMACS executable found" 2>&1
   exit 1
fi

if [ ! -x "$XEMACS" ]; then
   echo "Failed to $act, $XEMACS is not executable" 2>&1
   exit 1
fi

echo  "XEMACS            = $XEMACS"
export XEMACS

PATH=$OLD_PATH




