#!/bin/sh

Prior_XEMACS="$XEMACS"

#########################################################################

OLD_PATH=$PATH
PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:/usr/local/bin:${PATH}

XEMACS=`which xemacs`

if [ -z "$XEMACS" ]; then
   echo "Failed to $act, no XEMACS executable found" 2>&1
   exit 1
fi

if [ ! -x "$XEMACS" ]; then
   echo "Failed to $act, $XEMACS is not executable" 2>&1
   exit 1
fi
PATH=$OLD_PATH

export XEMACS

#########################################################################

echo ""
echo "prior XEMACS: $Prior_XEMACS"
echo "final XEMACS: $XEMACS"
echo ""





