SymbolMatching_Oblig = obligations MatchingSpecs#SymbolMatching

Symbols_Ref_Oblig = obligations MatchingRefinements#Symbols_Ref

WordMatching_Ref0_Oblig = obligations MatchingRefinements#WordMatching_Ref0

FindMatches_Ref0_Oblig = obligations MatchingRefinements#FindMatches_Ref0
