#!/bin/bash --noprofile

# The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
# files. See "man bash" for details. 

# Use the directory of this file as the value of SPECWARE4
SPECWARE4=`pwd`
export SPECWARE4

# Ensure SPECWARE4 is set to full pathname:

case "$SPECWARE4" in
    /*) : ok;;
    *)  SPECWARE4="`pwd`/$SPECWARE4";;
esac

# Ensure SWPATH is set

if [ -z "$SWPATH" ]; then
  SWPATH="/"
  export SWPATH
fi

if [ -z "$EMACS" ]; then
   for L in /Applications/Isabelle2011-1.app/Contents/Resources/Emacs.app/Contents/MacOS/Emacs "$HOME"/Applications/Isabelle2011-1.app/Contents/Resources/Emacs-23.app/Contents/MacOS/Emacs /Applications/Emacs.app/Contents/MacOS/Emacs; do
      if [ -x "$L" ]; then
         EMACS="$L"; break
      fi
   done
fi

if [ -z "$EMACS" ]; then
    EMACS=`which emacs`
    if [ -z "$EMACS" ]; then
	EMACS="/usr/bin/emacs"
    fi
fi

LISP_EXECUTABLE="$SPECWARE4"/Specware4.sbclexe
LISP_HEAP_IMAGE=NONE
LISP_DIRECTORY="$SPECWARE4"/
SPECWARE_INIT_FORM=NIL
export LISP_EXECUTABLE
export LISP_HEAP_IMAGE
export LISP_DIRECTORY
export SPECWARE_INIT_FORM

echo SPECWARE4=$SPECWARE4


# Load specware emacs files, do command line options (e.g. load and
# start Isabelle and then run-specware4

$EMACS -l $SPECWARE4/Library/IO/Emacs/load-slime.el $* -f run-specware4&
