#!/bin/bash --noprofile

# The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
# files. See "man bash" for details. 
source ~/.bashrc
SCRIPTDIR=`/usr/bin/dirname $0`/../../..
EMACS_SPECWARE="$SCRIPTDIR"/Emacs_Specware
cd "$SCRIPTDIR"

# Isabelle, fink, darwinports
PATH=/Applications/Isabelle2011.app/Isabelle/bin:/sw/bin:/opt/local/bin:/opt/local/sbin:$HOME/Applications/Isabelle2011.app/Isabelle/bin:${PATH}

isabelle emacs -p $EMACS_SPECWARE $* 