#!/bin/bash --noprofile

# The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
# files. See "man bash" for details. 
source ~/.bashrc
SCRIPTDIR=`/usr/bin/dirname $0`/../../..
XEMACS_SPECWARE="$SCRIPTDIR"/XEmacs_Specware
cd "$SCRIPTDIR"

isabelle-interface -p $XEMACS_SPECWARE $* 