#!/bin/bash --noprofile

# The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
# files. See "man bash" for details. 

# Use the directory of this file as the value of SPECWARE4
SPECWARE4=`/usr/bin/dirname $0`
export SPECWARE4

# Ensure SPECWARE4 is set to full pathname:

case "$SPECWARE4" in
    /*) : ok;;
    *)  SPECWARE4="`pwd`/$SPECWARE4";;
esac

# Ensure SWPATH is set

if [ -z "$SWPATH" ]; then
  SWPATH="/"
  export SWPATH
fi

# Try to find lisp executable:

if [ -z "$LISP" ]; then
   for L in /Applications/sbcl/bin/sbcl /usr/local/bin/sbcl "$HOME"/bin/sbcl /bin/lisp; do
      if [ -x "$L" ]; then
         LISP="$L"; break
      fi
   done
fi

if [ -z "$LISP" ]; then
   echo "Failed to $act, no LISP executable found" 2>&1
   exit 1
fi

if [ ! -x "$LISP" ]; then
   echo "Failed to $act, $LISP is not executable" 2>&1
   exit 1
fi

LISP_DIR=`dirname "$LISP"`
LISP_EXECUTABLE="$LISP"
LISP_HEAP_IMAGE="$SPECWARE4"/Specware4.sbclexe
LISP_DIRECTORY="$SPECWARE4"/
export LISP_EXECUTABLE
export LISP_HEAP_IMAGE
export LISP_DIRECTORY

echo SPECWARE4=$SPECWARE4


# Load specware emacs files, do command line options (e.g. load and
# start Isabelle and then run-specware4

xemacs -l $SPECWARE4/Library/IO/Emacs/load-slime.el $* -f run-specware4&
