#!/bin/bash --noprofile
(shopt -s igncr) 2>/dev/null && shopt -s igncr;  # Ignore cr's

# The --noprofile inhibits loading of ~/.bash_profile and ~/.profile
# files. See "man bash" for details. 

# Load specware emacs files, do command line options (e.g. load and
# start Isabelle and then run-specware4

emacs -l "$SPECWARE4"/Library/IO/Emacs/load-slime.el $* -f run-specware4&
