#!/bin/sh
(shopt -s igncr) 2>/dev/null && shopt -s igncr;  # Ignore cr's

act='launch Specware in SBCL (no XEmacs)'

########################################################################

OLD_PATH=$PATH
PATH=/bin:/usr/bin:/etc:/sbin:/usr/sbin:/usr/local/bin:${PATH}

# Use the directory of this file as the default value of SPECWARE4
# Note: $0 may refer to Specware or SpecwareShell script invoking this...

INVOKED_HERE=`dirname "$0"`
cd "$INVOKED_HERE"
HERE="`pwd`"
PATH="$OLD_PATH"

########################################################################

. "$HERE/Find_SPECWARE4"
. "$HERE/Update_Path"
. "$HERE/Update_SWPATH"
. "$HERE/Find_Specware_App_SBCL"


########################################################################

"$LISP_EXECUTABLE" --dynamic-space-size 900 --eval "(progn (setq Emacs::*use-emacs-interface?* nil) (Specware::initializeSpecware-0) (SWShell::specware-shell t) (sb-unix:unix-exit 0))"
