/*
 * ImportCustomizer.java
 *
 * Created on February 17, 2003, 7:01 PM
 */

package edu.kestrel.netbeans.nodes;

/**
 *
 * @author  weilyn
 */
public class ImportCustomizer extends javax.swing.JPanel {
    
    /** Creates new customizer ImportCustomizer */
    public ImportCustomizer() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
