#!/bin/sh

INVOKED_HERE=`dirname $0`
cd "$INVOKED_HERE"
HERE=`pwd`
cd "$HERE"

if [ "$1" == "" ]; then
  VERBOSE=nil
else
  VERBOSE=t
fi

echo "SPECWARE4    = $SPECWARE4"
echo "DISTRIBUTION = $DISTRIBUTION"

export LISP_MODE=${LISP_MODE:-SBCL}
 . $SPECWARE4/Scripts/unix/Verify_$LISP_MODE

echo "LISP_MODE    = $LISP_MODE"

if [ -z "$SPECWARE4" ]; then
  echo "SPECWARE4 not defined"
  exit -1
fi

if [ -z "$DISTRIBUTION" ]; then
  echo "DISTRIBUTION not defined"
  exit -1
fi

if [ ! -d "$SPECWARE4" ]; then
  echo "Can't find Specware4 directory: $SPECWARE4"
  exit -1
fi

if [ ! -d "$DISTRIBUTION" ]; then
  echo "Can't find distribution directory: $DISTRIBUTION"
  exit -1
fi

if [ -z $LISP_MODE ]; then
  echo "Build_Specware_Linux_Distribution:  LISP_MODE undefined"
  exit -1
fi

. "$SPECWARE4"/Applications/Specware/bin/unix/Verify_Specware_Variables
. "$SPECWARE4"/Scripts/unix/Verify_$LISP_MODE

BOOTSTRAP_IMAGE="$BIN_DIR"/Bootstrap.$IMAGE_EXTENSION
SPECWARE4_IMAGE="$BIN_DIR"/Specware4.$IMAGE_EXTENSION
SPECWARE_BASE_LISP="$SPECWARE4"/Applications/Specware/Specware4-base.lisp
SPECWARE_LISP="$SPECWARE4"/Applications/Specware/lisp/Specware4.lisp

cd "$HERE"

$BATCH_LISP <<EOF
	(load "BuildSpecwareDistribution.lisp")
	(build-specware-release $VERBOSE)
	#+ACL(exit)
	#-ACL(quit)
EOF

